#!/usr/bin/env python3
"""Add missing raid bosses to bosses.ts before the dynamax section."""

SRC = 'src/data/bosses.ts'

# Read existing file
with open(SRC, 'r', encoding='utf-8') as f:
    content = f.read()

# Find insertion point: before the dynamax comment
MARKER = '  // 極巨化團體戰'
idx = content.find(MARKER)
if idx == -1:
    raise RuntimeError('Cannot find dynamax marker')

before = content[:idx]
after = content[idx:]

# New raid bosses to add
NEW_BOSSES = """  // ---- 5星傳說團體戰 (追加) ----
  {
    id: 'lugia',
    name: { 'zh-TW': '洛奇亞', en: 'Lugia', ja: 'ルギア' },
    aliases: ['洛奇亞', '路基亞', '海皇'],
    category: 'raid',
    tier: 5,
    types: ['psychic', 'flying'],
    cp_range: { min: 2028, max: 2115, weather_min: 2535, weather_max: 2645 },
    weaknesses: ['electric', 'ice', 'rock', 'ghost', 'dark'],
    recommendation: 'SS',
    rec_reason: '防禦之王，PVP 大師聯盟頂級。氣旋攻擊是限定招式。刷高 IV 價值極高。',
    pve_rating: 3,
    pvp_rating: 5,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-11-01',
    rotation_end: '',
    current: false,
    pokemon_id: 249,
    counters: [
      { pokemon_id: 644, name: { 'zh-TW': '捷克羅姆', en: 'Zekrom', ja: 'ゼクロム' }, types: ['dragon', 'electric'], fast_move: { name: '充電光束', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 21.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '殘忍揮擊', type: 'dark' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 466, name: { 'zh-TW': '電擊魔獸', en: 'Electivire', ja: 'エレキブル' }, types: ['electric'], fast_move: { name: '電擊', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '惡之波動', type: 'dark' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 243, name: { 'zh-TW': '雷公', en: 'Raikou', ja: 'ライコウ' }, types: ['electric'], fast_move: { name: '電擊', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 18.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'ho-oh',
    name: { 'zh-TW': '鳳王', en: 'Ho-Oh', ja: 'ホウオウ' },
    aliases: ['鳳王', '鳳凰'],
    category: 'raid',
    tier: 5,
    types: ['fire', 'flying'],
    cp_range: { min: 2155, max: 2244, weather_min: 2694, weather_max: 2806 },
    weaknesses: ['rock', 'water', 'electric'],
    recommendation: 'SS',
    rec_reason: '聖焰是限定招式，火系 PVE 頂級。PVP 大師聯盟也實用。岩石雙倍弱點好打。',
    pve_rating: 4,
    pvp_rating: 4,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-12-01',
    rotation_end: '',
    current: false,
    pokemon_id: 250,
    counters: [
      { pokemon_id: 409, name: { 'zh-TW': '戰槌龍', en: 'Rampardos', ja: 'ラムパルド' }, types: ['rock'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 24.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 464, name: { 'zh-TW': '超甲狂犀', en: 'Rhyperior', ja: 'ドサイドン' }, types: ['ground', 'rock'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩石砲', type: 'rock' }, dps: 20.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 639, name: { 'zh-TW': '代拉基翁', en: 'Terrakion', ja: 'テラキオン' }, types: ['rock', 'fighting'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 19.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 382, name: { 'zh-TW': '蓋歐卡', en: 'Kyogre', ja: 'カイオーガ' }, types: ['water'], fast_move: { name: '水瀑', type: 'water' }, charged_move: { name: '衝浪', type: 'water' }, dps: 19.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 644, name: { 'zh-TW': '捷克羅姆', en: 'Zekrom', ja: 'ゼクロム' }, types: ['dragon', 'electric'], fast_move: { name: '充電光束', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 18.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'darkrai',
    name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' },
    aliases: ['達克萊伊', '黑暗萊伊'],
    category: 'raid',
    tier: 5,
    types: ['dark'],
    cp_range: { min: 2048, max: 2136, weather_min: 2560, weather_max: 2671 },
    weaknesses: ['fighting', 'bug', 'fairy'],
    recommendation: 'SSS',
    rec_reason: 'PVE 最強暗系打手之一。暗影球+出奇一擊極強。打超能/幽靈系必備。必抓多隻！',
    pve_rating: 5,
    pvp_rating: 4,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-10-01',
    rotation_end: '',
    current: false,
    pokemon_id: 491,
    counters: [
      { pokemon_id: 68, name: { 'zh-TW': '怪力', en: 'Machamp', ja: 'カイリキー' }, types: ['fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 22.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 448, name: { 'zh-TW': '路卡利歐', en: 'Lucario', ja: 'ルカリオ' }, types: ['fighting', 'steel'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '波導彈', type: 'fighting' }, dps: 23.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 534, name: { 'zh-TW': '修繕老頭', en: 'Conkeldurr', ja: 'ローブシン' }, types: ['fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 21.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 257, name: { 'zh-TW': '火焰雞', en: 'Blaziken', ja: 'バシャーモ' }, types: ['fire', 'fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 282, name: { 'zh-TW': '沙奈朵', en: 'Gardevoir', ja: 'サーナイト' }, types: ['psychic', 'fairy'], fast_move: { name: '迷惑', type: 'fairy' }, charged_move: { name: '魔法閃耀', type: 'fairy' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 639, name: { 'zh-TW': '代拉基翁', en: 'Terrakion', ja: 'テラキオン' }, types: ['rock', 'fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '近身戰', type: 'fighting' }, dps: 19.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'heatran',
    name: { 'zh-TW': '席多藍恩', en: 'Heatran', ja: 'ヒードラン' },
    aliases: ['席多藍恩', '火山龜'],
    category: 'raid',
    tier: 5,
    types: ['fire', 'steel'],
    cp_range: { min: 2058, max: 2145, weather_min: 2573, weather_max: 2681 },
    weaknesses: ['ground', 'water', 'fighting'],
    recommendation: 'S',
    rec_reason: 'PVP 大師聯盟實用。地面四倍弱點好打。火系+鋼系抗性極多。值得刷高 IV。',
    pve_rating: 3,
    pvp_rating: 4,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-09-01',
    rotation_end: '',
    current: false,
    pokemon_id: 485,
    counters: [
      { pokemon_id: 383, name: { 'zh-TW': '固拉多', en: 'Groudon', ja: 'グラードン' }, types: ['ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '斷崖之劍', type: 'ground' }, dps: 24.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 445, name: { 'zh-TW': '烈咬陸鯊', en: 'Garchomp', ja: 'ガブリアス' }, types: ['dragon', 'ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '大地之力', type: 'ground' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 464, name: { 'zh-TW': '超甲狂犀', en: 'Rhyperior', ja: 'ドサイドン' }, types: ['ground', 'rock'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '地震', type: 'ground' }, dps: 20.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 530, name: { 'zh-TW': '龍頭地鼠', en: 'Excadrill', ja: 'ドリュウズ' }, types: ['ground', 'steel'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '地震', type: 'ground' }, dps: 20.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 382, name: { 'zh-TW': '蓋歐卡', en: 'Kyogre', ja: 'カイオーガ' }, types: ['water'], fast_move: { name: '水瀑', type: 'water' }, charged_move: { name: '衝浪', type: 'water' }, dps: 19.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 260, name: { 'zh-TW': '巨沼怪', en: 'Swampert', ja: 'ラグラージ' }, types: ['water', 'ground'], fast_move: { name: '水槍', type: 'water' }, charged_move: { name: '水砲', type: 'water' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
    ],
  },
  {
    id: 'cresselia',
    name: { 'zh-TW': '克雷色利亞', en: 'Cresselia', ja: 'クレセリア' },
    aliases: ['克雷色利亞', '月亮'],
    category: 'raid',
    tier: 5,
    types: ['psychic'],
    cp_range: { min: 1633, max: 1712, weather_min: 2041, weather_max: 2141 },
    weaknesses: ['bug', 'ghost', 'dark'],
    recommendation: 'S',
    rec_reason: 'PVP 超級/大師聯盟頂級坦克。防禦極高難打但值得刷高 IV。暗系是主要打手。',
    pve_rating: 2,
    pvp_rating: 5,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-11-01',
    rotation_end: '',
    current: false,
    pokemon_id: 488,
    counters: [
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 22.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 94, name: { 'zh-TW': '耿鬼', en: 'Gengar', ja: 'ゲンガー' }, types: ['ghost', 'poison'], fast_move: { name: '暗影爪', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 22.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: true, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '殘忍揮擊', type: 'dark' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 609, name: { 'zh-TW': '水晶燈火靈', en: 'Chandelure', ja: 'シャンデラ' }, types: ['ghost', 'fire'], fast_move: { name: '妖火', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 635, name: { 'zh-TW': '三頭龍', en: 'Hydreigon', ja: 'サザンドラ' }, types: ['dark', 'dragon'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '暴風', type: 'dark' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '惡之波動', type: 'dark' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'xerneas',
    name: { 'zh-TW': '哲爾尼亞斯', en: 'Xerneas', ja: 'ゼルネアス' },
    aliases: ['哲爾尼亞斯', 'X鹿'],
    category: 'raid',
    tier: 5,
    types: ['fairy'],
    cp_range: { min: 2160, max: 2249, weather_min: 2701, weather_max: 2812 },
    weaknesses: ['poison', 'steel'],
    recommendation: 'SS',
    rec_reason: 'PVP 大師聯盟妖精系之王。只弱毒和鋼，抗性極多。月亮之力是核心招。必刷高 IV。',
    pve_rating: 3,
    pvp_rating: 5,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-12-01',
    rotation_end: '',
    current: false,
    pokemon_id: 716,
    counters: [
      { pokemon_id: 376, name: { 'zh-TW': '巨金怪', en: 'Metagross', ja: 'メタグロス' }, types: ['steel', 'psychic'], fast_move: { name: '子彈拳', type: 'steel' }, charged_move: { name: '彗星拳', type: 'steel' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 649, name: { 'zh-TW': '蓋諾賽克特', en: 'Genesect', ja: 'ゲノセクト' }, types: ['bug', 'steel'], fast_move: { name: '金屬爪', type: 'steel' }, charged_move: { name: '加農光砲', type: 'steel' }, dps: 20.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 94, name: { 'zh-TW': '耿鬼', en: 'Gengar', ja: 'ゲンガー' }, types: ['ghost', 'poison'], fast_move: { name: '舔', type: 'ghost' }, charged_move: { name: '污泥波', type: 'poison' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 407, name: { 'zh-TW': '羅絲雷朵', en: 'Roserade', ja: 'ロズレイド' }, types: ['grass', 'poison'], fast_move: { name: '毒擊', type: 'poison' }, charged_move: { name: '污泥炸彈', type: 'poison' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 530, name: { 'zh-TW': '龍頭地鼠', en: 'Excadrill', ja: 'ドリュウズ' }, types: ['ground', 'steel'], fast_move: { name: '金屬爪', type: 'steel' }, charged_move: { name: '鐵頭', type: 'steel' }, dps: 18.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 483, name: { 'zh-TW': '帝牙盧卡', en: 'Dialga', ja: 'ディアルガ' }, types: ['steel', 'dragon'], fast_move: { name: '金屬爪', type: 'steel' }, charged_move: { name: '鐵頭', type: 'steel' }, dps: 18.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'yveltal',
    name: { 'zh-TW': '伊裴爾塔爾', en: 'Yveltal', ja: 'イベルタル' },
    aliases: ['伊裴爾塔爾', 'Y鳥'],
    category: 'raid',
    tier: 5,
    types: ['dark', 'flying'],
    cp_range: { min: 2073, max: 2160, weather_min: 2591, weather_max: 2701 },
    weaknesses: ['electric', 'ice', 'rock', 'fairy'],
    recommendation: 'SSS',
    rec_reason: 'PVE 暗系頂級打手+PVP 大師聯盟頂級。暗+飛雙系極為泛用。必抓多隻！',
    pve_rating: 5,
    pvp_rating: 5,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2026-01-01',
    rotation_end: '',
    current: false,
    pokemon_id: 717,
    counters: [
      { pokemon_id: 644, name: { 'zh-TW': '捷克羅姆', en: 'Zekrom', ja: 'ゼクロム' }, types: ['dragon', 'electric'], fast_move: { name: '充電光束', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 21.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 409, name: { 'zh-TW': '戰槌龍', en: 'Rampardos', ja: 'ラムパルド' }, types: ['rock'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 22.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 282, name: { 'zh-TW': '沙奈朵', en: 'Gardevoir', ja: 'サーナイト' }, types: ['psychic', 'fairy'], fast_move: { name: '迷惑', type: 'fairy' }, charged_move: { name: '魔法閃耀', type: 'fairy' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 466, name: { 'zh-TW': '電擊魔獸', en: 'Electivire', ja: 'エレキブル' }, types: ['electric'], fast_move: { name: '電擊', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 473, name: { 'zh-TW': '象牙豬', en: 'Mamoswine', ja: 'マンムー' }, types: ['ice', 'ground'], fast_move: { name: '粉雪', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'landorus-therian',
    name: { 'zh-TW': '土地雲(靈獸)', en: 'Landorus (Therian)', ja: 'ランドロス(れいじゅう)' },
    aliases: ['土地雲', '地雲', '靈獸土地雲'],
    category: 'raid',
    tier: 5,
    types: ['ground', 'flying'],
    cp_range: { min: 2151, max: 2241, weather_min: 2688, weather_max: 2801 },
    weaknesses: ['ice', 'water'],
    recommendation: 'SSS',
    rec_reason: 'PVE 最強地面系打手！冰系雙倍弱點好打。地面系 DPS 之王，必抓多隻養滿。',
    pve_rating: 5,
    pvp_rating: 3,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-10-01',
    rotation_end: '',
    current: false,
    pokemon_id: 645,
    counters: [
      { pokemon_id: 473, name: { 'zh-TW': '象牙豬', en: 'Mamoswine', ja: 'マンムー' }, types: ['ice', 'ground'], fast_move: { name: '粉雪', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 25.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 471, name: { 'zh-TW': '冰伊布', en: 'Glaceon', ja: 'グレイシア' }, types: ['ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 21.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 382, name: { 'zh-TW': '蓋歐卡', en: 'Kyogre', ja: 'カイオーガ' }, types: ['water'], fast_move: { name: '水瀑', type: 'water' }, charged_move: { name: '衝浪', type: 'water' }, dps: 19.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 131, name: { 'zh-TW': '拉普拉斯', en: 'Lapras', ja: 'ラプラス' }, types: ['water', 'ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '冰凍光束', type: 'ice' }, dps: 17.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 130, name: { 'zh-TW': '暴鯉龍', en: 'Gyarados', ja: 'ギャラドス' }, types: ['water', 'flying'], fast_move: { name: '水瀑', type: 'water' }, charged_move: { name: '水砲', type: 'water' }, dps: 17.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'kyurem',
    name: { 'zh-TW': '酋雷姆', en: 'Kyurem', ja: 'キュレム' },
    aliases: ['酋雷姆', '冰龍'],
    category: 'raid',
    tier: 5,
    types: ['dragon', 'ice'],
    cp_range: { min: 2042, max: 2130, weather_min: 2553, weather_max: 2663 },
    weaknesses: ['fighting', 'rock', 'steel', 'dragon', 'fairy'],
    recommendation: 'S',
    rec_reason: '龍+冰雙系傳說。弱點多但打手選擇也多。值得刷高 IV 等待合體形態。',
    pve_rating: 3,
    pvp_rating: 3,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-08-01',
    rotation_end: '',
    current: false,
    pokemon_id: 646,
    counters: [
      { pokemon_id: 376, name: { 'zh-TW': '巨金怪', en: 'Metagross', ja: 'メタグロス' }, types: ['steel', 'psychic'], fast_move: { name: '子彈拳', type: 'steel' }, charged_move: { name: '彗星拳', type: 'steel' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 448, name: { 'zh-TW': '路卡利歐', en: 'Lucario', ja: 'ルカリオ' }, types: ['fighting', 'steel'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '波導彈', type: 'fighting' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 282, name: { 'zh-TW': '沙奈朵', en: 'Gardevoir', ja: 'サーナイト' }, types: ['psychic', 'fairy'], fast_move: { name: '迷惑', type: 'fairy' }, charged_move: { name: '魔法閃耀', type: 'fairy' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 384, name: { 'zh-TW': '烈空坐', en: 'Rayquaza', ja: 'レックウザ' }, types: ['dragon', 'flying'], fast_move: { name: '龍尾', type: 'dragon' }, charged_move: { name: '逆鱗', type: 'dragon' }, dps: 20.0, accessibility: 'legendary', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 639, name: { 'zh-TW': '代拉基翁', en: 'Terrakion', ja: 'テラキオン' }, types: ['rock', 'fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '近身戰', type: 'fighting' }, dps: 19.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 483, name: { 'zh-TW': '帝牙盧卡', en: 'Dialga', ja: 'ディアルガ' }, types: ['steel', 'dragon'], fast_move: { name: '龍息', type: 'dragon' }, charged_move: { name: '流星群', type: 'dragon' }, dps: 18.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'genesect',
    name: { 'zh-TW': '蓋諾賽克特', en: 'Genesect', ja: 'ゲノセクト' },
    aliases: ['蓋諾賽克特', '蓋諾'],
    category: 'raid',
    tier: 5,
    types: ['bug', 'steel'],
    cp_range: { min: 1916, max: 1999, weather_min: 2395, weather_max: 2499 },
    weaknesses: ['fire'],
    recommendation: 'A',
    rec_reason: '只弱火系一個屬性。有多種驅動器形態。色違收集價值。火系輕鬆打。',
    pve_rating: 3,
    pvp_rating: 2,
    min_trainers: 2,
    solo_possible: false,
    last_appeared: '2025-07-01',
    rotation_end: '',
    current: false,
    pokemon_id: 649,
    counters: [
      { pokemon_id: 643, name: { 'zh-TW': '雷希拉姆', en: 'Reshiram', ja: 'レシラム' }, types: ['dragon', 'fire'], fast_move: { name: '火焰牙', type: 'fire' }, charged_move: { name: '交錯火焰', type: 'fire' }, dps: 24.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 609, name: { 'zh-TW': '水晶燈火靈', en: 'Chandelure', ja: 'シャンデラ' }, types: ['ghost', 'fire'], fast_move: { name: '火焰旋渦', type: 'fire' }, charged_move: { name: '過熱', type: 'fire' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 257, name: { 'zh-TW': '火焰雞', en: 'Blaziken', ja: 'バシャーモ' }, types: ['fire', 'fighting'], fast_move: { name: '火焰旋渦', type: 'fire' }, charged_move: { name: '爆炸燃燒', type: 'fire' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 383, name: { 'zh-TW': '固拉多', en: 'Groudon', ja: 'グラードン' }, types: ['ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '噴火', type: 'fire' }, dps: 20.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 250, name: { 'zh-TW': '鳳王', en: 'Ho-Oh', ja: 'ホウオウ' }, types: ['fire', 'flying'], fast_move: { name: '引誘', type: 'fire' }, charged_move: { name: '聖焰', type: 'fire' }, dps: 19.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: true, community_day_move: false },
      { pokemon_id: 6, name: { 'zh-TW': '噴火龍', en: 'Charizard', ja: 'リザードン' }, types: ['fire', 'flying'], fast_move: { name: '火焰旋渦', type: 'fire' }, charged_move: { name: '爆炸燃燒', type: 'fire' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
    ],
  },
  // ---- Mega 團體戰 (6星) ----
  {
    id: 'mega-gengar',
    name: { 'zh-TW': 'Mega耿鬼', en: 'Mega Gengar', ja: 'メガゲンガー' },
    aliases: ['Mega耿鬼', '超級耿鬼'],
    category: 'raid',
    tier: 6,
    types: ['ghost', 'poison'],
    cp_range: { min: 1566, max: 1644, weather_min: 1958, weather_max: 2055 },
    weaknesses: ['ground', 'ghost', 'psychic', 'dark'],
    recommendation: 'SSS',
    rec_reason: 'PVE 最強幽靈系 Mega，DPS 冠絕所有 Mega。打超能力/幽靈系必備 Mega 能量。',
    pve_rating: 5,
    pvp_rating: 2,
    min_trainers: 2,
    solo_possible: false,
    last_appeared: '2025-12-01',
    rotation_end: '',
    current: false,
    pokemon_id: 94,
    counters: [
      { pokemon_id: 383, name: { 'zh-TW': '固拉多', en: 'Groudon', ja: 'グラードン' }, types: ['ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '斷崖之劍', type: 'ground' }, dps: 22.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 150, name: { 'zh-TW': '超夢', en: 'Mewtwo', ja: 'ミュウツー' }, types: ['psychic'], fast_move: { name: '念力', type: 'psychic' }, charged_move: { name: '精神擊破', type: 'psychic' }, dps: 22.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: true, community_day_move: false },
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 445, name: { 'zh-TW': '烈咬陸鯊', en: 'Garchomp', ja: 'ガブリアス' }, types: ['dragon', 'ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '大地之力', type: 'ground' }, dps: 20.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '殘忍揮擊', type: 'dark' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 530, name: { 'zh-TW': '龍頭地鼠', en: 'Excadrill', ja: 'ドリュウズ' }, types: ['ground', 'steel'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '地震', type: 'ground' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'mega-rayquaza',
    name: { 'zh-TW': 'Mega烈空坐', en: 'Mega Rayquaza', ja: 'メガレックウザ' },
    aliases: ['Mega烈空坐', '超級烈空坐', 'MRay'],
    category: 'raid',
    tier: 6,
    types: ['dragon', 'flying'],
    cp_range: { min: 3153, max: 3264, weather_min: 3942, weather_max: 4080 },
    weaknesses: ['ice', 'rock', 'dragon', 'fairy'],
    recommendation: 'SSS',
    rec_reason: '全遊戲 PVE 最強寶可夢，龍系/飛行系 DPS 之王。冰系雙倍弱點。不惜一切代價打！',
    pve_rating: 5,
    pvp_rating: 3,
    min_trainers: 4,
    solo_possible: false,
    last_appeared: '2025-08-01',
    rotation_end: '',
    current: false,
    pokemon_id: 384,
    counters: [
      { pokemon_id: 473, name: { 'zh-TW': '象牙豬', en: 'Mamoswine', ja: 'マンムー' }, types: ['ice', 'ground'], fast_move: { name: '粉雪', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 24.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 471, name: { 'zh-TW': '冰伊布', en: 'Glaceon', ja: 'グレイシア' }, types: ['ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 282, name: { 'zh-TW': '沙奈朵', en: 'Gardevoir', ja: 'サーナイト' }, types: ['psychic', 'fairy'], fast_move: { name: '迷惑', type: 'fairy' }, charged_move: { name: '魔法閃耀', type: 'fairy' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 131, name: { 'zh-TW': '拉普拉斯', en: 'Lapras', ja: 'ラプラス' }, types: ['water', 'ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '冰凍光束', type: 'ice' }, dps: 17.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 376, name: { 'zh-TW': '巨金怪', en: 'Metagross', ja: 'メタグロス' }, types: ['steel', 'psychic'], fast_move: { name: '子彈拳', type: 'steel' }, charged_move: { name: '彗星拳', type: 'steel' }, dps: 17.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
    ],
  },
  {
    id: 'mega-garchomp',
    name: { 'zh-TW': 'Mega烈咬陸鯊', en: 'Mega Garchomp', ja: 'メガガブリアス' },
    aliases: ['Mega烈咬陸鯊', '超級烈咬陸鯊'],
    category: 'raid',
    tier: 6,
    types: ['dragon', 'ground'],
    cp_range: { min: 2174, max: 2264, weather_min: 2718, weather_max: 2830 },
    weaknesses: ['ice', 'dragon', 'fairy'],
    recommendation: 'SSS',
    rec_reason: 'PVE 頂級地面/龍系 Mega，冰系雙倍弱點好打。Mega 加成極為實用，必打。',
    pve_rating: 5,
    pvp_rating: 3,
    min_trainers: 2,
    solo_possible: false,
    last_appeared: '2025-11-01',
    rotation_end: '',
    current: false,
    pokemon_id: 445,
    counters: [
      { pokemon_id: 473, name: { 'zh-TW': '象牙豬', en: 'Mamoswine', ja: 'マンムー' }, types: ['ice', 'ground'], fast_move: { name: '粉雪', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 25.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 471, name: { 'zh-TW': '冰伊布', en: 'Glaceon', ja: 'グレイシア' }, types: ['ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 21.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 384, name: { 'zh-TW': '烈空坐', en: 'Rayquaza', ja: 'レックウザ' }, types: ['dragon', 'flying'], fast_move: { name: '龍尾', type: 'dragon' }, charged_move: { name: '逆鱗', type: 'dragon' }, dps: 21.0, accessibility: 'legendary', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 282, name: { 'zh-TW': '沙奈朵', en: 'Gardevoir', ja: 'サーナイト' }, types: ['psychic', 'fairy'], fast_move: { name: '迷惑', type: 'fairy' }, charged_move: { name: '魔法閃耀', type: 'fairy' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 131, name: { 'zh-TW': '拉普拉斯', en: 'Lapras', ja: 'ラプラス' }, types: ['water', 'ice'], fast_move: { name: '冰之牙', type: 'ice' }, charged_move: { name: '冰凍光束', type: 'ice' }, dps: 17.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'mega-tyranitar',
    name: { 'zh-TW': 'Mega班基拉斯', en: 'Mega Tyranitar', ja: 'メガバンギラス' },
    aliases: ['Mega班基拉斯', '超級班基拉斯'],
    category: 'raid',
    tier: 6,
    types: ['rock', 'dark'],
    cp_range: { min: 2103, max: 2191, weather_min: 2629, weather_max: 2739 },
    weaknesses: ['fighting', 'water', 'grass', 'ground', 'bug', 'steel', 'fairy'],
    recommendation: 'SSS',
    rec_reason: 'PVE 最強暗系/岩石系 Mega。格鬥雙倍弱點易打。Mega 加成極為泛用，必打！',
    pve_rating: 5,
    pvp_rating: 3,
    min_trainers: 2,
    solo_possible: false,
    last_appeared: '2025-12-01',
    rotation_end: '',
    current: false,
    pokemon_id: 248,
    counters: [
      { pokemon_id: 448, name: { 'zh-TW': '路卡利歐', en: 'Lucario', ja: 'ルカリオ' }, types: ['fighting', 'steel'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '波導彈', type: 'fighting' }, dps: 25.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 534, name: { 'zh-TW': '修繕老頭', en: 'Conkeldurr', ja: 'ローブシン' }, types: ['fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 23.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 68, name: { 'zh-TW': '怪力', en: 'Machamp', ja: 'カイリキー' }, types: ['fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 22.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 257, name: { 'zh-TW': '火焰雞', en: 'Blaziken', ja: 'バシャーモ' }, types: ['fire', 'fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 22.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 286, name: { 'zh-TW': '斗笠菇', en: 'Breloom', ja: 'キノガッサ' }, types: ['grass', 'fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 22.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 214, name: { 'zh-TW': '赫拉克羅斯', en: 'Heracross', ja: 'ヘラクロス' }, types: ['bug', 'fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '近身戰', type: 'fighting' }, dps: 21.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'mega-metagross',
    name: { 'zh-TW': 'Mega巨金怪', en: 'Mega Metagross', ja: 'メガメタグロス' },
    aliases: ['Mega巨金怪', '超級巨金怪'],
    category: 'raid',
    tier: 6,
    types: ['steel', 'psychic'],
    cp_range: { min: 2078, max: 2166, weather_min: 2597, weather_max: 2708 },
    weaknesses: ['fire', 'ground', 'ghost', 'dark'],
    recommendation: 'SSS',
    rec_reason: 'PVE 最強鋼系 Mega，彗星拳+Mega 加成極為泛用。打妖精/冰/岩王牌。必打！',
    pve_rating: 5,
    pvp_rating: 3,
    min_trainers: 3,
    solo_possible: false,
    last_appeared: '2025-11-01',
    rotation_end: '',
    current: false,
    pokemon_id: 376,
    counters: [
      { pokemon_id: 383, name: { 'zh-TW': '固拉多', en: 'Groudon', ja: 'グラードン' }, types: ['ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '斷崖之劍', type: 'ground' }, dps: 22.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 643, name: { 'zh-TW': '雷希拉姆', en: 'Reshiram', ja: 'レシラム' }, types: ['dragon', 'fire'], fast_move: { name: '火焰牙', type: 'fire' }, charged_move: { name: '交錯火焰', type: 'fire' }, dps: 21.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 609, name: { 'zh-TW': '水晶燈火靈', en: 'Chandelure', ja: 'シャンデラ' }, types: ['ghost', 'fire'], fast_move: { name: '妖火', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 20.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 445, name: { 'zh-TW': '烈咬陸鯊', en: 'Garchomp', ja: 'ガブリアス' }, types: ['dragon', 'ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '大地之力', type: 'ground' }, dps: 20.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 635, name: { 'zh-TW': '三頭龍', en: 'Hydreigon', ja: 'サザンドラ' }, types: ['dark', 'dragon'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '暴風', type: 'dark' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
    ],
  },
  // ---- 3星團體戰 (追加) ----
  {
    id: 'alakazam',
    name: { 'zh-TW': '胡地', en: 'Alakazam', ja: 'フーディン' },
    aliases: ['胡地'],
    category: 'raid',
    tier: 3,
    types: ['psychic'],
    cp_range: { min: 1666, max: 1747, weather_min: 2083, weather_max: 2184 },
    weaknesses: ['bug', 'ghost', 'dark'],
    recommendation: 'S',
    rec_reason: 'Mega 胡地 PVE 超能力系頂級。Solo 可行，刷 Mega 能量和高 IV 價值高。',
    pve_rating: 4,
    pvp_rating: 2,
    min_trainers: 1,
    solo_possible: true,
    last_appeared: '2025-11-01',
    rotation_end: '',
    current: false,
    pokemon_id: 65,
    counters: [
      { pokemon_id: 94, name: { 'zh-TW': '耿鬼', en: 'Gengar', ja: 'ゲンガー' }, types: ['ghost', 'poison'], fast_move: { name: '暗影爪', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 23.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: true, community_day_move: false },
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 22.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '殘忍揮擊', type: 'dark' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 609, name: { 'zh-TW': '水晶燈火靈', en: 'Chandelure', ja: 'シャンデラ' }, types: ['ghost', 'fire'], fast_move: { name: '妖火', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 635, name: { 'zh-TW': '三頭龍', en: 'Hydreigon', ja: 'サザンドラ' }, types: ['dark', 'dragon'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '暴風', type: 'dark' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '惡之波動', type: 'dark' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'togetic',
    name: { 'zh-TW': '波克基古', en: 'Togetic', ja: 'トゲチック' },
    aliases: ['波克基古'],
    category: 'raid',
    tier: 3,
    types: ['fairy', 'flying'],
    cp_range: { min: 924, max: 982, weather_min: 1155, weather_max: 1228 },
    weaknesses: ['electric', 'ice', 'poison', 'rock', 'steel'],
    recommendation: 'S',
    rec_reason: '進化成波克基斯是 PVP 頂級妖精系。刷高 IV 波克比糖價值極高。',
    pve_rating: 3,
    pvp_rating: 5,
    min_trainers: 1,
    solo_possible: true,
    last_appeared: '2025-09-01',
    rotation_end: '',
    current: false,
    pokemon_id: 176,
    counters: [
      { pokemon_id: 376, name: { 'zh-TW': '巨金怪', en: 'Metagross', ja: 'メタグロス' }, types: ['steel', 'psychic'], fast_move: { name: '子彈拳', type: 'steel' }, charged_move: { name: '彗星拳', type: 'steel' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 466, name: { 'zh-TW': '電擊魔獸', en: 'Electivire', ja: 'エレキブル' }, types: ['electric'], fast_move: { name: '電擊', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 409, name: { 'zh-TW': '戰槌龍', en: 'Rampardos', ja: 'ラムパルド' }, types: ['rock'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 20.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 407, name: { 'zh-TW': '羅絲雷朵', en: 'Roserade', ja: 'ロズレイド' }, types: ['grass', 'poison'], fast_move: { name: '毒擊', type: 'poison' }, charged_move: { name: '污泥炸彈', type: 'poison' }, dps: 18.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 644, name: { 'zh-TW': '捷克羅姆', en: 'Zekrom', ja: 'ゼクロム' }, types: ['dragon', 'electric'], fast_move: { name: '充電光束', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 19.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 473, name: { 'zh-TW': '象牙豬', en: 'Mamoswine', ja: 'マンムー' }, types: ['ice', 'ground'], fast_move: { name: '粉雪', type: 'ice' }, charged_move: { name: '雪崩', type: 'ice' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'scyther',
    name: { 'zh-TW': '飛天螳螂', en: 'Scyther', ja: 'ストライク' },
    aliases: ['飛天螳螂'],
    category: 'raid',
    tier: 3,
    types: ['bug', 'flying'],
    cp_range: { min: 1546, max: 1631, weather_min: 1933, weather_max: 2039 },
    weaknesses: ['rock', 'fire', 'electric', 'ice', 'flying'],
    recommendation: 'A',
    rec_reason: '進化成巨鉗螳螂 PVP 實用。Mega 巨鉗螳螂蟲/鋼系好用。Solo 容易。',
    pve_rating: 2,
    pvp_rating: 3,
    min_trainers: 1,
    solo_possible: true,
    last_appeared: '2025-10-01',
    rotation_end: '',
    current: false,
    pokemon_id: 123,
    counters: [
      { pokemon_id: 409, name: { 'zh-TW': '戰槌龍', en: 'Rampardos', ja: 'ラムパルド' }, types: ['rock'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 24.0, accessibility: 'common', is_shadow: true, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 20.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 464, name: { 'zh-TW': '超甲狂犀', en: 'Rhyperior', ja: 'ドサイドン' }, types: ['ground', 'rock'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩石砲', type: 'rock' }, dps: 19.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 643, name: { 'zh-TW': '雷希拉姆', en: 'Reshiram', ja: 'レシラム' }, types: ['dragon', 'fire'], fast_move: { name: '火焰牙', type: 'fire' }, charged_move: { name: '交錯火焰', type: 'fire' }, dps: 19.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 466, name: { 'zh-TW': '電擊魔獸', en: 'Electivire', ja: 'エレキブル' }, types: ['electric'], fast_move: { name: '電擊', type: 'electric' }, charged_move: { name: '狂野伏特', type: 'electric' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 639, name: { 'zh-TW': '代拉基翁', en: 'Terrakion', ja: 'テラキオン' }, types: ['rock', 'fighting'], fast_move: { name: '打落', type: 'rock' }, charged_move: { name: '岩崩', type: 'rock' }, dps: 18.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  // ---- 1星團體戰 (追加) ----
  {
    id: 'klink',
    name: { 'zh-TW': '齒輪兒', en: 'Klink', ja: 'ギアル' },
    aliases: ['齒輪兒'],
    category: 'raid',
    tier: 1,
    types: ['steel'],
    cp_range: { min: 546, max: 594, weather_min: 683, weather_max: 743 },
    weaknesses: ['fire', 'fighting', 'ground'],
    recommendation: 'A',
    rec_reason: '只能從團體戰和蛋取得，圖鑑必打。色違可得。收集價值高。',
    pve_rating: 1,
    pvp_rating: 1,
    min_trainers: 1,
    solo_possible: true,
    last_appeared: '2026-01-01',
    rotation_end: '',
    current: false,
    pokemon_id: 599,
    counters: [
      { pokemon_id: 383, name: { 'zh-TW': '固拉多', en: 'Groudon', ja: 'グラードン' }, types: ['ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '地震', type: 'ground' }, dps: 20.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 257, name: { 'zh-TW': '火焰雞', en: 'Blaziken', ja: 'バシャーモ' }, types: ['fire', 'fighting'], fast_move: { name: '火焰旋渦', type: 'fire' }, charged_move: { name: '爆炸燃燒', type: 'fire' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 445, name: { 'zh-TW': '烈咬陸鯊', en: 'Garchomp', ja: 'ガブリアス' }, types: ['dragon', 'ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '大地之力', type: 'ground' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 68, name: { 'zh-TW': '怪力', en: 'Machamp', ja: 'カイリキー' }, types: ['fighting'], fast_move: { name: '雙倍奉還', type: 'fighting' }, charged_move: { name: '爆裂拳', type: 'fighting' }, dps: 18.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 643, name: { 'zh-TW': '雷希拉姆', en: 'Reshiram', ja: 'レシラム' }, types: ['dragon', 'fire'], fast_move: { name: '火焰牙', type: 'fire' }, charged_move: { name: '交錯火焰', type: 'fire' }, dps: 18.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 609, name: { 'zh-TW': '水晶燈火靈', en: 'Chandelure', ja: 'シャンデラ' }, types: ['ghost', 'fire'], fast_move: { name: '火焰旋渦', type: 'fire' }, charged_move: { name: '過熱', type: 'fire' }, dps: 18.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'litwick',
    name: { 'zh-TW': '燭光靈', en: 'Litwick', ja: 'ヒトモシ' },
    aliases: ['燭光靈', '蠟燭'],
    category: 'raid',
    tier: 1,
    types: ['ghost', 'fire'],
    cp_range: { min: 542, max: 590, weather_min: 678, weather_max: 737 },
    weaknesses: ['water', 'ground', 'rock', 'ghost', 'dark'],
    recommendation: 'SS',
    rec_reason: '進化成水晶燈火靈是 PVE 頂級幽靈/火系打手！強烈建議刷高 IV。',
    pve_rating: 5,
    pvp_rating: 2,
    min_trainers: 1,
    solo_possible: true,
    last_appeared: '2026-02-01',
    rotation_end: '',
    current: false,
    pokemon_id: 607,
    counters: [
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '殘忍揮擊', type: 'dark' }, dps: 19.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 383, name: { 'zh-TW': '固拉多', en: 'Groudon', ja: 'グラードン' }, types: ['ground'], fast_move: { name: '泥巴射擊', type: 'ground' }, charged_move: { name: '地震', type: 'ground' }, dps: 18.5, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 382, name: { 'zh-TW': '蓋歐卡', en: 'Kyogre', ja: 'カイオーガ' }, types: ['water'], fast_move: { name: '水瀑', type: 'water' }, charged_move: { name: '衝浪', type: 'water' }, dps: 18.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 635, name: { 'zh-TW': '三頭龍', en: 'Hydreigon', ja: 'サザンドラ' }, types: ['dark', 'dragon'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '暴風', type: 'dark' }, dps: 17.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '惡之波動', type: 'dark' }, dps: 18.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
  {
    id: 'espurr',
    name: { 'zh-TW': '妙喵', en: 'Espurr', ja: 'ニャスパー' },
    aliases: ['妙喵'],
    category: 'raid',
    tier: 1,
    types: ['psychic'],
    cp_range: { min: 636, max: 688, weather_min: 795, weather_max: 860 },
    weaknesses: ['bug', 'ghost', 'dark'],
    recommendation: 'B',
    rec_reason: '進化成超能妙喵有男女差異外觀。收集圖鑑和性別差異用。色違已開放。',
    pve_rating: 1,
    pvp_rating: 2,
    min_trainers: 1,
    solo_possible: true,
    last_appeared: '2025-12-01',
    rotation_end: '',
    current: false,
    pokemon_id: 677,
    counters: [
      { pokemon_id: 491, name: { 'zh-TW': '達克萊伊', en: 'Darkrai', ja: 'ダークライ' }, types: ['dark'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 22.0, accessibility: 'legendary', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 94, name: { 'zh-TW': '耿鬼', en: 'Gengar', ja: 'ゲンガー' }, types: ['ghost', 'poison'], fast_move: { name: '暗影爪', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 21.0, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: true, community_day_move: false },
      { pokemon_id: 248, name: { 'zh-TW': '班基拉斯', en: 'Tyranitar', ja: 'バンギラス' }, types: ['rock', 'dark'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '殘忍揮擊', type: 'dark' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: true, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 609, name: { 'zh-TW': '水晶燈火靈', en: 'Chandelure', ja: 'シャンデラ' }, types: ['ghost', 'fire'], fast_move: { name: '妖火', type: 'ghost' }, charged_move: { name: '暗影球', type: 'ghost' }, dps: 20.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
      { pokemon_id: 635, name: { 'zh-TW': '三頭龍', en: 'Hydreigon', ja: 'サザンドラ' }, types: ['dark', 'dragon'], fast_move: { name: '咬住', type: 'dark' }, charged_move: { name: '暴風', type: 'dark' }, dps: 18.0, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: true },
      { pokemon_id: 461, name: { 'zh-TW': '瑪狃拉', en: 'Weavile', ja: 'マニューラ' }, types: ['dark', 'ice'], fast_move: { name: '出奇一擊', type: 'dark' }, charged_move: { name: '惡之波動', type: 'dark' }, dps: 18.5, accessibility: 'common', is_shadow: false, is_mega: false, elite_tm_required: false, community_day_move: false },
    ],
  },
"""

with open(SRC, 'w', encoding='utf-8') as f:
    f.write(before)
    f.write(NEW_BOSSES)
    f.write(after)

# Verify
with open(SRC, 'r', encoding='utf-8') as f:
    final = f.read()

raid_count = final.count("category: 'raid'")
dynamax_count = final.count("category: 'dynamax'")
giga_count = final.count("category: 'gigantamax'")
total = raid_count + dynamax_count + giga_count

print(f"Raid bosses: {raid_count}")
print(f"Dynamax bosses: {dynamax_count}")
print(f"Gigantamax bosses: {giga_count}")
print(f"Total: {total}")
print(f"Lines: {final.count(chr(10))}")
